# params.yaml
data_ingestion:
  test_size: 0.2

feature_engineering:
  max_features: 10000
  max_df: 0.9
  min_df: 5
  ngram_range: [1, 2]

model_building:
  solver: 'saga'
  penalty: 'elasticnet'
  C: 1.0
  l1_ratio: 0.5
  