import os
import json
from typing import Dict, Any
from dotenv import load_dotenv

from src.logger import get_logger

logger = get_logger(__name__)
load_dotenv()


def setup_mlflow():
    """Configure MLflow credentials if available."""
    token = os.getenv("DAGSHUB_TOKEN") or os.getenv("sentiment_analysis")
    tracking_uri = os.getenv("MLFLOW_TRACKING_URI")

    if not tracking_uri:
        repo_owner = os.getenv("DAGSHUB_REPO_OWNER")
        repo_name = os.getenv("DAGSHUB_REPO_NAME", "sentiment-analysis")
        if repo_owner:
            tracking_uri = f"https://dagshub.com/{repo_owner}/{repo_name}.mlflow"

    if token:
        os.environ["MLFLOW_TRACKING_USERNAME"] = token
        os.environ["MLFLOW_TRACKING_PASSWORD"] = token

    if tracking_uri:
        try:
            import mlflow
            mlflow.set_tracking_uri(tracking_uri)
            return True, tracking_uri
        except Exception as e:
            logger.warning("Failed to configure MLflow tracking URI: %s", e)

    return False, ""


def load_model_info(file_path: str = "reports/experiment_info.json") -> Dict[str, Any]:
    """Load experiment info generated by model evaluation stage."""
    if not os.path.exists(file_path):
        raise FileNotFoundError(f"Experiment info file not found: {file_path}")
    with open(file_path, "r", encoding="utf-8") as f:
        return json.load(f)


def register_model_in_registry(model_name: str, model_info: Dict[str, Any], target_stage: str = "Staging") -> bool:
    """Register trained model into MLflow Model Registry."""
    run_id = model_info.get("run_id")
    model_path = model_info.get("model_path", "model")

    if not run_id or run_id == "local-run":
        logger.info("Local run detected (%s); skipping remote MLflow model registry step.", run_id)
        return False

    import mlflow
    from mlflow.tracking import MlflowClient

    model_uri = f"runs:/{run_id}/{model_path}"
    logger.info("Registering model from URI '%s' as '%s'...", model_uri, model_name)

    try:
        model_version = mlflow.register_model(model_uri, model_name)
        logger.info("Model '%s' registered with version %s", model_name, model_version.version)

        client = MlflowClient()
        client.transition_model_version_stage(
            name=model_name,
            version=model_version.version,
            stage=target_stage,
            archive_existing_versions=True
        )
        logger.info("Model '%s' (v%s) transitioned to %s.", model_name, model_version.version, target_stage)
        return True
    except Exception as e:
        logger.error("Failed to register model in MLflow: %s", e)
        raise


def main():
    try:
        mlflow_enabled, _ = setup_mlflow()
        if not mlflow_enabled:
            logger.info("MLflow is not configured; skipping remote model registration.")
            return

        model_info = load_model_info("reports/experiment_info.json")
        model_name = os.getenv("MLFLOW_MODEL_NAME", "sentiment_model")
        target_stage = os.getenv("MLFLOW_TARGET_STAGE", "Staging")
        register_model_in_registry(model_name, model_info, target_stage=target_stage)
        logger.info("Model registration process completed successfully.")

    except Exception as e:
        logger.error("Model registration process failed: %s", e, exc_info=True)
        raise


if __name__ == "__main__":
    main()
