name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to Azure VM
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.VM_IP }}
          username: ${{ secrets.VM_USER }}
          key: ${{ secrets.VM_SSH_KEY }}
          script: |
            # Pull latest image from ACR
            sudo docker pull mymlopsv2.azurecr.io/capstone-app:latest
            # Stop existing container if running
            sudo docker stop capstone-app || true
            sudo docker rm capstone-app || true
            # Run new container
            sudo docker run -d -p 5000:5000 \
              -e sentiment_analysis=${{ secrets.sentiment_analysis }} \
              --name capstone-app \
              mymlopsv2.azurecr.io/capstone-app:latest
